server:
  port: 8080
database:
  username: postgres
  password: 123456
  host: 127.0.0.1
  port: 5432
  name: postgres
  schema: demo
jwt:
  secret: 12345678
  expiration: 3600
  audience: audience
  issuer: issuer
